<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>0e9cae59-a45f-47da-8691-891a4ad8a62b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\modules\GamePersistence\GamePersistence.Application\GamePersistence.Application.csproj" />
    <ProjectReference Include="..\..\modules\GamePersistence\GamePersistence.Infrastructure\GamePersistence.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Identities\Identities.Application\Identities.Application.csproj" />
    <ProjectReference Include="..\..\modules\Identities\Identities.Infrastructure\Identities.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Locations\Locations.Application\Locations.Application.csproj" />
    <ProjectReference Include="..\..\modules\Locations\Locations.Infrastructure\Locations.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Matches\Matches.Application\Matches.Application.csproj" />
    <ProjectReference Include="..\..\modules\Seasons\Seasons.Application\Seasons.Application.csproj" />
    <ProjectReference Include="..\..\modules\Seasons\Seasons.Infrastructure\Seasons.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Teams\Teams.Application\Teams.Application.csproj" />
    <ProjectReference Include="..\..\modules\Teams\Teams.Infrastructure\Teams.Infrastructure.csproj" />
  </ItemGroup>

</Project>
