<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.Data\Common.Data.csproj" />
    <ProjectReference Include="..\..\Common\Common.Features\Common.Features.csproj" />
    <ProjectReference Include="..\Seasons.Infrastructure\Seasons.Infrastructure.csproj" />
  </ItemGroup>

</Project>
