<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Common\Common.Features\Common.Features.csproj" />
        <ProjectReference Include="..\..\Matches\Matches.Application\Matches.Application.csproj" />
        <ProjectReference Include="..\..\Seasons\Seasons.Application\Seasons.Application.csproj" />
        <ProjectReference Include="..\..\Teams\Teams.Application\Teams.Application.csproj" />
        <ProjectReference Include="..\Leagues.Infrastructure\Leagues.Infrastructure.csproj" />
    </ItemGroup>


</Project>
