// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectFootballSim.Team.Infrastructure.Database;

#nullable disable

namespace ProjectFootballSim.Team.Infrastructure.Migrations
{
    [DbContext(typeof(TeamDbContext))]
    [Migration("20260729140109_TeamInit")]
    partial class TeamInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectFootballSim.Team.Domain.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Attack");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Defence");

                    b.Property<int>("Midfield")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Midfield");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
