<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Match.Domain\Match.Domain.csproj" />
      <InternalsVisibleTo Include="$(AssemblyName).Tests" />
  </ItemGroup>

</Project>
