<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\Common.Data\Common.Data.csproj" />
      <ProjectReference Include="..\Teams.Domain\Teams.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
